### ISSUE TITLE
繁體中文

### ISSUE THREAD

**Issue by shiuanyue** [SamaraFleurety/MIS_Arknights_FullPack#12]
製作了語言包
https://send.internxt.com/download/2910328e-818d-4a19-ae4a-016039008237?code=36fa018aee8b6c6cda7707cbee29879b4a3f7ec66b60b9948d0007cd675c9e5b

**Comment by SamaraFleurety** [comment]
你是想将其整合进本体吗？还是怎么

**Comment by shiuanyue** [comment]
是的
我也會弄好M.I.S. - Arknights 的繁中語言包 
整合進本體

**Comment by SamaraFleurety** [comment]
那等会我给放进本体。
希望在steam界面署名吗？如果要的话请留下想署的名或者个人页链接之类的。

**Comment by shiuanyue** [comment]
放個ID就可以了

**Comment by shiuanyue** [comment]
連結8/20過期
https://send.internxt.com/download/3c3b1d7b-1b7c-482d-bba3-57cc85f239af?code=8a7c3364ae5ed3fdca446833f8f096d51ac1125fce7dc086e2e36379c58f6747

**Comment by SamaraFleurety** [comment]
感谢翻译，下个版本会装进去

**Comment by shiuanyue** [comment]
雖然我能翻譯的部分都檢查了一遍
但界面沒有正常顯示

**Comment by shiuanyue** [comment]
![image](https://github.com/SamaraFleurety/Rimworld_Arknights/assets/39412432/6617a95d-7646-4b08-bb1d-cb19ecb98b3b)

**Comment by shiuanyue** [comment]
![image](https://github.com/SamaraFleurety/Rimworld_Arknights/assets/39412432/41fc29de-a257-4594-8b05-e5bb219d1107)

**Comment by SamaraFleurety** [comment]
不好意思！可能是我使用了仅简体中文的字库的原因。我会在下个版本更改兼容繁体中文的字库。感谢测试。
